disabled = false
languageCode = "ja"
languageName = "日本語"
weight = 1
title = "ワセリンの部屋"

[params]
displayName = "JA"
isoCode = "ja"
rtl = false
dateFormat = "2006年1月2日"
logo = "icon.png"

["params.author"]
name = "ワセリン"
image = "profile.jpg"
headline = "絵描いたり、色々やるし色々好きです。<br><br>waslyn0502★gmail.com (★→@)"
bio = "絵描いたり、色々やるし色々好きです。"

[[params.author.links]]
  x-twitter = "https://x.com/wasabi_apple"
[[params.author.links]]
  instagram = "https://www.instagram.com/wasssslyn/"
[[params.author.links]]
  niconico = "https://www.nicovideo.jp/user/70670553"
[[params.author.links]]
  pixiv="https://www.pixiv.net/users/67607687"
